name: build
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Update lock
        run: |
          pipenv lock          
      - name: Install dependencies
        run: |
          pipenv install --deploy --dev
      - name: Run test suite
        run: |
          pipenv run pytest
      - name: Install Pytest
        run: |
          pipenv install --dev pytest-cov
      - name: Run Tests with Coverage
        run: pipenv run pytest --cov
